### ISSUE TITLE
Config example里多了个逗号导致json格式错误

### ISSUE THREAD

**Issue by skstudying** [FoloToy/folotoy-doc#28]
中英各一处如下：

https://github.com/FoloToy/folotoy-doc/blob/4d2253cffa003bcc7b66726401b57cee9c354dff/docs/configuration/roles_config.mdx#L284

https://github.com/FoloToy/folotoy-doc/blob/4d2253cffa003bcc7b66726401b57cee9c354dff/i18n/zh/docusaurus-plugin-content-docs/current/configuration/roles_config.mdx#L282

**Comment by lewangdev** [comment]
fixed at 993d65e8295eb82708c13c05bdb92736d66301f0.

Thank you for your help.
