### ISSUE TITLE
如何播放第三方音频?

### ISSUE THREAD

**Issue by bxb100** [FoloToy/folotoy-doc#78]
固件说支持, 但是直接返回链接无法使用

https://github.com/FoloToy/folotoy-bin/releases 
`支持播放url长度在256个字符以内的第三方音乐链接`

**Comment by lewangdev** [comment]
参考这里 https://docs.folotoy.com/zh/docs/integrations/mqtt

**Comment by bxb100** [comment]
> 参考这里 [docs.folotoy.com/zh/docs/integrations/mqtt](https://docs.folotoy.com/zh/docs/integrations/mqtt)

ok

支持的音频格式是看这个项目? https://github.com/schreibfaul1/ESP32-audioI2S

**Comment by bxb100** [comment]
哎, mitu 的内存太小了, 1MB 的音频直接出现各种异常
